version: '3.7'

services:
  app:
    container_name: app
    build: .docker/app
    environment:
      - PHP_IDE_CONFIG=serverName=shop
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - .docker/app/.bashrc:/home/www-data/.bashrc
      - .docker/app/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    container_name: nginx
    build: ./.docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - 49100:80
    links:
      - app
  mysql:
    build: ./.docker/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
    ports:
      - 49101:3306

  redis:
    container_name: redis
    image: redis:7.0-alpine

  mailer:
    image: schickling/mailcatcher
    ports:
      - 49102:1080
