<?php

namespace ContainerWXjx10M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pkyz8qyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pkyz8qy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pkyz8qy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\WheelsBrandCrudController::autocomplete' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::batchDelete' => ['privates', '.service_locator.esmk6IF', 'get_ServiceLocator_Esmk6IFService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureActions' => ['privates', '.service_locator.R8Qy2_.', 'get_ServiceLocator_R8Qy2_Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureAssets' => ['privates', '.service_locator.XdMPwIJ', 'get_ServiceLocator_XdMPwIJService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureCrud' => ['privates', '.service_locator.XpfeRo6', 'get_ServiceLocator_XpfeRo6Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureFilters' => ['privates', '.service_locator.OGjUKCt', 'get_ServiceLocator_OGjUKCtService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureResponseParameters' => ['privates', '.service_locator.W.c5h2_', 'get_ServiceLocator_W_C5h2Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::createEditForm' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::createEditFormBuilder' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::createIndexQueryBuilder' => ['privates', '.service_locator.ENGuM7_', 'get_ServiceLocator_ENGuM7Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::createNewForm' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::createNewFormBuilder' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::delete' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::deleteEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::detail' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::edit' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::index' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::new' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::persistEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::renderFilters' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController::updateEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandDashboardController::configureUserMenu' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:autocomplete' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:batchDelete' => ['privates', '.service_locator.esmk6IF', 'get_ServiceLocator_Esmk6IFService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureActions' => ['privates', '.service_locator.R8Qy2_.', 'get_ServiceLocator_R8Qy2_Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureAssets' => ['privates', '.service_locator.XdMPwIJ', 'get_ServiceLocator_XdMPwIJService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureCrud' => ['privates', '.service_locator.XpfeRo6', 'get_ServiceLocator_XpfeRo6Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureFilters' => ['privates', '.service_locator.OGjUKCt', 'get_ServiceLocator_OGjUKCtService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureResponseParameters' => ['privates', '.service_locator.W.c5h2_', 'get_ServiceLocator_W_C5h2Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:createEditForm' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:createEditFormBuilder' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:createIndexQueryBuilder' => ['privates', '.service_locator.ENGuM7_', 'get_ServiceLocator_ENGuM7Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:createNewForm' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:createNewFormBuilder' => ['privates', '.service_locator.riFbGaB', 'get_ServiceLocator_RiFbGaBService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:delete' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:deleteEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:detail' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:edit' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:index' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:new' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:persistEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:renderFilters' => ['privates', '.service_locator.kEvhmk9', 'get_ServiceLocator_KEvhmk9Service', true],
            'App\\Controller\\Admin\\WheelsBrandCrudController:updateEntity' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\Admin\\WheelsBrandDashboardController:configureUserMenu' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\Admin\\WheelsBrandCrudController::autocomplete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::batchDelete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureActions' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureAssets' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureCrud' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureFilters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::configureResponseParameters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::createEditForm' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::createNewForm' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::delete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::deleteEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::detail' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::edit' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::index' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::new' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::persistEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::renderFilters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController::updateEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandDashboardController::configureUserMenu' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:autocomplete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:batchDelete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureActions' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureAssets' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureCrud' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureFilters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:configureResponseParameters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:createEditForm' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:createNewForm' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:delete' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:deleteEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:detail' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:edit' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:index' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:new' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:persistEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:renderFilters' => '?',
            'App\\Controller\\Admin\\WheelsBrandCrudController:updateEntity' => '?',
            'App\\Controller\\Admin\\WheelsBrandDashboardController:configureUserMenu' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
