<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnmEBDS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnmEBDS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFnmEBDS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFnmEBDS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFnmEBDS\App_KernelDevDebugContainer([
    'container.build_hash' => 'FnmEBDS',
    'container.build_id' => '145e2054',
    'container.build_time' => 1699298276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnmEBDS');
