<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMs7zmX5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMs7zmX5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMs7zmX5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMs7zmX5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMs7zmX5\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ms7zmX5',
    'container.build_id' => '291985ab',
    'container.build_time' => 1699121781,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMs7zmX5');
